name: Restrict Merge to Master

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: test 브랜치에서 생성된 PR인지 확인
        if: github.event.pull_request.head.ref != 'test'
        run: |
          echo "This PR is not from the 'test' branch."
          exit 1